spring:
  data:
    mongo:
      uri: mongodb://localhost:27018/db
    cosmos:
      uri: mongodb://localhost:C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==@localhost:10255/db?ssl=true

management.security.enabled: false