management.security.enabled: false

info:
  build:
    version: @project.version@
    name: @project.name@
  app:
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@

spring:
  data:
    mongo:
      uri: mongodb://localhost:27017/dbTest
    cosmos:
      uri: mongodb://localhost:27017/dbTest2

azure:
  servicebus:
    connection-string: Endpoint=sb://sb-name.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SQ8TpsTP5nt777Jih9RK9lxfAmq2g0M3Y/zH9+o6TSg=
    queue-name: queue-name
    queue-receive-mode: peeklock